import type { ChapterConfig, ChapterNode } from './types'

const nodes: ChapterNode[] = [
  // ===== 開場對話：海克絲興奮地說要換 Logo =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '早安！昨天跟合夥人聊到半夜，我們決定要換 Logo。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '今日任務文件：https://hackmd.io/@hexschool/backend-camp-day4',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '蛤？不是才剛做好嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(拉了張椅子坐下來) 你看喔，現在的 Logo 叫 LiveFit+，但我們昨天討論了一下，覺得這個「+」現在用掉太可惜了。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '可惜？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '對啊，我們才剛起步，現在應該先叫 LiveFit 就好。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '等之後平台做起來了、會員變多了、功能更完整了，再升級成 LiveFit+。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那個「+」代表的是進化版，就像 iPhone 變成 iPhone Plus 一樣。現在就用掉，以後要升級就沒梗了。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '原來如此！所以先把「+」拿掉，等 2.0 再加回來？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '沒錯！設計師已經做好新版 Logo 了，檔名是 logo-text-v2.png，你幫我換上去。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(指著螢幕上的 Logo) 話說，如果我現在要你改這個 Logo，你知道要去哪裡找檔案嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '呃⋯⋯這個專案資料夾這麼多層，Logo 到底放在哪？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(微微一笑) 別急，改東西之前，要先搞懂專案的資料夾結構。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: 'Logo 這種圖片屬於「靜態資源」，不會隨著使用者操作而變動的東西，通常會放在 public/ 資料夾裡。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '等等，什麼是「靜態資源」？那有「動態」的嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(露出欣慰的微笑) 問得好！這個觀念很重要，搞懂之後你才知道要去哪裡改東西。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '來，我先說一個災難故事給你聽⋯⋯',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 災難故事：教練資料寫死的問題 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '你知道前任後端工程師是怎麼處理教練列表的嗎？',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '不知道⋯⋯怎麼做的？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '他把所有教練的資料都「寫死」在前端程式碼裡。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '什麼王小明、李小華、50 個教練的名字、照片、專長⋯⋯全部直接寫在 HTML 裡面。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '這樣有什麼問題嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '問題可大了！有一天我打電話給他說：「王小明教練離職了，幫我從網站上移除。」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '他說好，然後打開程式碼，找到那段 HTML，刪掉。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '我又說：「對了，李小華要改名叫李大華，順便更新他的照片。」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '他說好⋯⋯繼續改程式碼。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '我又說：「還有，我們新簽了 10 個教練，資料 Email 給你了。」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '然後他就崩潰了。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '(冒冷汗) 我好像知道問題在哪了⋯⋯',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '沒錯！每次教練資料變動，都要改程式碼、重新部署網站。萬一改錯，網站就爆炸了。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },

  // ===== 選擇題：測試理解 =====
  {
    type: 'choice',
    prompt: '你覺得教練資料應該放在哪裡比較好？',
    options: [
      {
        id: 'a',
        label: '繼續寫死在 HTML 裡',
        response: '(搖頭) 這樣每次資料變動都要改程式碼，太沒效率了，而且容易出錯。',
        responseExpression: 'sigh',
        isCorrect: false,
      },
      {
        id: 'b',
        label: '放在資料庫，透過 API 取得',
        response: '(拍手) 答對了！把資料存在資料庫，需要的時候透過 API 取得，這樣改資料就不用動到程式碼了。',
        responseExpression: 'praise',
        isCorrect: true,
      },
      {
        id: 'c',
        label: '寫在 CSS 檔案裡',
        response: '(忍不住笑) CSS 是用來設定樣式的，不是存資料的地方啦！',
        responseExpression: 'biglaugh',
        isCorrect: false,
      },
      {
        id: 'd',
        label: '放在 public/ 資料夾',
        response: 'public/ 資料夾是放「靜態資源」的，像是圖片、Logo。教練資料會經常變動，不適合放這裡。',
        responseExpression: 'normal',
        isCorrect: false,
      },
    ],
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 解釋靜態 vs 動態 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '你剛剛提到的「靜態」和「動態」，這是很重要的觀念。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '讓我用簡報解釋給你聽。',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 靜態 vs 動態 互動簡報 =====
  {
    type: 'interactiveSlide',
    slideId: 'static-dynamic',
    title: '靜態 vs 動態 互動實驗室',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 簡報後對話 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '怎麼樣？現在知道靜態和動態的差別了吧！',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '原來如此！Logo 是靜態的，去 public/ 找；教練資料是動態的，要去資料庫改。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(滿意地點頭) 完全正確！你學得很快嘛。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那我再考考你幾個問題，確認你真的懂了。',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 測驗題目 =====
  {
    type: 'quiz',
    title: '靜態資源 vs 動態資料 小考',
    scene: 'meeting',
    coachExpression: 'praise',
    questions: [
      {
        id: 'q1',
        prompt: '如果把所有教練資料「寫死」在前端程式碼裡，會發生什麼問題？',
        options: [
          { id: 'a', label: '網站跑得比較快' },
          { id: 'b', label: '每次教練資料變動都要改程式碼並重新部署' },
          { id: 'c', label: '教練可以自己修改資料' },
        ],
        correctOptionId: 'b',
        explanation: '寫死的資料每次變動都需要改程式碼並重新部署，非常沒效率，而且容易出錯。',
      },
      {
        id: 'q2',
        prompt: '為什麼教練資料不適合當作「靜態資源」？',
        options: [
          { id: 'a', label: '因為教練資料太大' },
          { id: 'b', label: '因為教練資料會經常變動（新增、修改、刪除）' },
          { id: 'c', label: '因為靜態資源比較貴' },
        ],
        correctOptionId: 'b',
        explanation: '教練會離職、新進、改名、換照片，資料經常變動，所以應該存在資料庫。',
      },
      {
        id: 'q3',
        prompt: '以下哪個屬於「靜態資源」？',
        options: [
          { id: 'a', label: '會員的個人資料' },
          { id: 'b', label: '網站的 Logo 圖片' },
          { id: 'c', label: '課程的預約紀錄' },
        ],
        correctOptionId: 'b',
        explanation: 'Logo 幾乎不會變動，屬於靜態資源。會員資料和預約紀錄會經常變動，是動態資料。',
      },
      {
        id: 'q4',
        prompt: '以下哪個屬於「動態資料」？',
        options: [
          { id: 'a', label: '網站的背景圖片' },
          { id: 'b', label: '網站的 favicon 小圖示' },
          { id: 'c', label: '教練列表' },
        ],
        correctOptionId: 'c',
        explanation: '教練列表會隨著教練新增或離職而變動，是動態資料，應該存在資料庫。',
      },
      {
        id: 'q5',
        prompt: '靜態資源通常放在專案的哪個資料夾？',
        options: [
          { id: 'a', label: 'src/pages/' },
          { id: 'b', label: 'public/ 或 src/assets/' },
          { id: 'c', label: 'node_modules/' },
        ],
        correctOptionId: 'b',
        explanation: '靜態資源通常放在 public/（不會被編譯）或 src/assets/（會被編譯處理）。',
      },
      {
        id: 'q6',
        prompt: '如果老闆說：「幫我把首頁的大圖換掉」，你應該？',
        options: [
          { id: 'a', label: '去資料庫修改' },
          { id: 'b', label: '去 public/ 或 assets/ 資料夾換圖片，並修改引用的程式碼' },
          { id: 'c', label: '重新安裝 Docker' },
        ],
        correctOptionId: 'b',
        explanation: '首頁大圖是靜態資源，去對應資料夾換檔案，並確認引用的程式碼改成新檔名。',
      },
      {
        id: 'q7',
        prompt: '在 LiveFit 專案中，Logo 圖片放在哪裡？',
        options: [
          { id: 'a', label: 'frontend/src/components/' },
          { id: 'b', label: 'frontend/public/' },
          { id: 'c', label: 'backend/images/' },
        ],
        correctOptionId: 'b',
        explanation: 'Logo 是靜態資源，放在 frontend/public/ 資料夾。',
      },
      {
        id: 'q8',
        prompt: '如果要修改網站使用的 Logo，除了換圖片檔案，還需要改什麼？',
        options: [
          { id: 'a', label: '只要換圖片就好，不用改其他東西' },
          { id: 'b', label: '找到引用這張圖片的程式碼，改成新的檔名' },
          { id: 'c', label: '重新安裝整個專案' },
        ],
        correctOptionId: 'b',
        explanation: '換圖片後，還要找到引用它的程式碼（如 LayoutHeader.vue）改成新檔名。',
      },
      {
        id: 'q9',
        prompt: '用 LiveFit 來比喻，「Logo」和「教練列表」分別對應什麼？',
        options: [
          { id: 'a', label: 'Logo = 動態資料，教練列表 = 靜態資源' },
          { id: 'b', label: 'Logo = 靜態資源，教練列表 = 動態資料' },
          { id: 'c', label: '兩個都是靜態資源' },
        ],
        correctOptionId: 'b',
        explanation: 'Logo 很少換（靜態資源），教練列表隨時可能變動（動態資料）。',
      },
      {
        id: 'q10',
        prompt: '動態資料的正確處理方式是？',
        options: [
          { id: 'a', label: '直接寫死在 HTML 裡面' },
          { id: 'b', label: '存在資料庫，前端透過 API 取得' },
          { id: 'c', label: '放在 public/ 資料夾' },
        ],
        correctOptionId: 'b',
        explanation: '動態資料應該存在資料庫，前端透過 API 請求後端，後端從資料庫取得資料再回傳。',
      },
    ],
  },

  // ===== 測驗完成後的對話 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(滿意地點頭) 很好！你已經掌握靜態和動態的觀念了。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那現在你應該知道怎麼換 Logo 了吧？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '知道了！去 frontend/public/ 找到圖片，然後去 LayoutHeader.vue 把檔名改成新的。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(拍手) 完全正確！',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '對了，設計師做好的新 Logo 在這裡，你先下載下來。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '這是新版 Logo（logo-text-v2.png），請在圖片上按右鍵 → 另存圖片',
    scene: 'meeting',
    coachExpression: 'normal',
    image: '/images/logo-text-v2.png',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '下載好之後，把這張圖片放到 frontend/public/ 資料夾裡面。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '然後打開 LayoutHeader.vue，把 Logo 的檔名從 logo-text.png 改成 logo-text-v2.png。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '了解！我這就去換 Logo。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '記得換完之後重新整理網頁，確認 Logo 有更新。如果沒變，可能是瀏覽器快取，按 Ctrl+F5 強制重新整理試試。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '對了，以後遇到要改東西，先問自己：這個東西會經常變動嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '會經常變動的，去資料庫改；不會變動的，去檔案改。搞清楚這點，找東西就快多了。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那接下來就拜託你嘍！加油！',
    scene: 'meeting',
    coachExpression: 'praise',
  },

  // ===== 慶祝完成 =====
  {
    type: 'celebration',
    chapterTitle: '第四天：改一個 Logo 而已',
    scene: 'meeting',
    coachExpression: 'praise',
  },
]

export const chapter4: ChapterConfig = {
  id: 4,
  title: '第四天：改一個 Logo 而已',
  nodes,
}
