import type { ChapterConfig, ChapterNode } from './types'

const nodes: ChapterNode[] = [
  // ===== 開場 =====
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '📋 今日任務文件：https://hackmd.io/bqy3W0jQSs-FdeesMNxIBw',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '(測試 LiveFit 功能中) 奇怪...我剛剛明明關掉瀏覽器了...',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '(重新打開網站) 欸？怎麼還是登入狀態？系統怎麼知道我是誰？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(走過來) 好問題！你發現了一個很重要的現象。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '這不是理所當然的嗎？每個網站登入後都這樣啊。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(搖搖頭) 其實 HTTP 本身是「無狀態」的——每次請求都是獨立的，伺服器根本不會記得你是誰！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '蛤？那為什麼我不用每次都重新登入？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(露出神秘的微笑) 這就要講到今天的主題了——JWT 和 LocalStorage！',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '簡單說，登入成功後伺服器會給你一張「號碼牌」，瀏覽器會把這張號碼牌存起來。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '之後你每次發請求，都帶著這張號碼牌，伺服器一看就知道你是誰了！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '號碼牌？聽起來像是餐廳取餐號碼。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(眼睛發亮) 對！這個比喻很棒！讓我用簡報詳細解釋給你聽。',
    scene: 'normal',
    coachExpression: 'praise',
  },

  // ===== 第一個互動簡報：JWT 通行證 =====
  {
    type: 'interactiveSlide',
    slideId: 'jwt-intro',
    title: 'JWT 通行證：用餐廳號碼牌理解身份驗證',
    scene: 'normal',
    coachExpression: 'normal',
  },

  // ===== 簡報後對話：銜接 JWT Storage =====
  {
    type: 'dialogue',
    speaker: '你',
    text: '原來如此！JWT 就像餐廳的號碼牌，登入時後端會給我一張，上面有我的資訊！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(點頭) 而且這張號碼牌有防偽章（Signature），是用後端的秘密印章蓋的！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '所以別人無法偽造！因為只有餐廳...不對，只有後端有那個秘密印章。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(滿意地微笑) 完全正確！而且那個秘密印章要放在 .env 保險箱裡，絕對不能上傳到網路上！',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '對對對！要用 .gitignore 把 .env 擋住！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(開心) 你學得很快！那你知道前端拿到 JWT 後，會存在哪裡嗎？',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '呃...存在...瀏覽器裡面？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '沒錯！瀏覽器有兩個常用的「儲物櫃」：LocalStorage 和 Cookie。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '讓我用 Chrome 開發者工具帶你實際看看！',
    scene: 'normal',
    coachExpression: 'normal',
  },

  // ===== 第二個互動簡報：JWT 存放位置 =====
  {
    type: 'interactiveSlide',
    slideId: 'jwt-storage',
    title: 'JWT 存放位置：瀏覽器的儲物櫃',
    scene: 'normal',
    coachExpression: 'normal',
  },

  // ===== 簡報後對話：銜接測驗 =====
  {
    type: 'dialogue',
    speaker: '你',
    text: '哇！原來用 Chrome 開發者工具就可以看到這些資料！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(點頭) 是的！Application 面板是個很實用的工具，可以看到 LocalStorage、Cookie、Session Storage 等資料。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: 'LocalStorage 和 Cookie 有什麼差別？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: 'LocalStorage 容量大（約 5MB），資料會永久保存，但不會自動帶上請求。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: 'Cookie 容量小（約 4KB），可以設定過期時間，而且每次請求會自動帶上！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '所以 JWT 可以存在 LocalStorage，也可以存在 Cookie？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(比讚) Bingo！兩種都可以，各有優缺點。LiveFit 用的是 LocalStorage。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(表情變認真) 對了，還有一件很重要的安全提醒...',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '什麼安全提醒？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: 'JWT 就像鑰匙，如果被別人偷走，他就能冒充你！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '所以離開電腦前一定要鎖定螢幕，不然別人打開 DevTools 就能看到你的 JWT！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '對！Mac 按 Cmd+Ctrl+Q，Windows 按 Win+L 就可以快速鎖定！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(比讚) 很好！這是在公司工作很重要的習慣！',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(滿意) 好，今天學了很多！讓我來考考你對這些概念的理解。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '(緊張) 又要考試了...',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(鼓勵) 別緊張！你剛剛的表現很不錯，相信自己！',
    scene: 'normal',
    coachExpression: 'praise',
  },

  // ===== 測驗 =====
  {
    type: 'quiz',
    title: 'Day 8 測驗：JWT 與身份驗證',
    scene: 'normal',
    coachExpression: 'normal',
    questions: [
      {
        id: 'q1',
        prompt: '為什麼關掉瀏覽器後重新打開，網站還是維持登入狀態？',
        options: [
          { id: 'a', label: '因為瀏覽器有存「號碼牌」（JWT），每次請求都會帶著它' },
          { id: 'b', label: '因為伺服器會自動記住你的電腦' },
          { id: 'c', label: '因為密碼存在瀏覽器裡' },
          { id: 'd', label: '因為網站有偷偷安裝軟體在你電腦' },
        ],
        correctOptionId: 'a',
        explanation: '登入時後端會給你一張「號碼牌」（JWT），瀏覽器把它存在 LocalStorage 或 Cookie，之後每次請求都帶著它，後端就知道你是誰。',
      },
      {
        id: 'q2',
        prompt: 'JWT 的全名是什麼？',
        options: [
          { id: 'a', label: 'Java Web Token' },
          { id: 'b', label: 'JSON Web Token' },
          { id: 'c', label: 'JavaScript Web Token' },
          { id: 'd', label: 'JSON Web Transfer' },
        ],
        correctOptionId: 'b',
        explanation: 'JWT 全名是 JSON Web Token，是一種用於身份驗證的數位憑證格式。',
      },
      {
        id: 'q3',
        prompt: '為什麼別人無法偽造你的 JWT？',
        options: [
          { id: 'a', label: '因為 JWT 有加密，別人看不到內容' },
          { id: 'b', label: '因為 JWT 上面有後端的「防偽章」，只有後端能蓋這個章' },
          { id: 'c', label: '因為 JWT 存在資料庫裡，別人拿不到' },
          { id: 'd', label: '因為 JWT 每秒都會自動更換' },
        ],
        correctOptionId: 'b',
        explanation: 'JWT 像餐廳號碼牌一樣，上面有後端的「防偽章」（Signature），這個章是用後端的秘密金鑰產生的，別人沒有金鑰就無法偽造。',
      },
      {
        id: 'q4',
        prompt: '後端的秘密金鑰（用來蓋防偽章的印章）應該放在哪裡？',
        options: [
          { id: 'a', label: '直接寫在程式碼裡' },
          { id: 'b', label: '放在 .env 檔案，並用 .gitignore 防止上傳' },
          { id: 'c', label: '放在 README.md 讓大家知道' },
          { id: 'd', label: '上傳到 GitHub 讓團隊成員都能看到' },
        ],
        correctOptionId: 'b',
        explanation: '秘密金鑰要存在 .env 檔案（保險箱）中，並用 .gitignore 防止上傳到網路上，不然全世界都能偽造你的 JWT！',
      },
      {
        id: 'q5',
        prompt: 'LocalStorage 和 Cookie 有什麼差異？',
        options: [
          { id: 'a', label: 'LocalStorage 容量大但不會自動帶上請求，Cookie 容量小但會自動帶上' },
          { id: 'b', label: 'LocalStorage 只能存數字，Cookie 只能存文字' },
          { id: 'c', label: 'LocalStorage 會自動刪除，Cookie 永久保存' },
          { id: 'd', label: 'LocalStorage 只有後端能讀，Cookie 只有前端能讀' },
        ],
        correctOptionId: 'a',
        explanation: 'LocalStorage 容量約 5MB，資料永久保存但不會自動帶上請求；Cookie 容量約 4KB，可設過期時間且每次請求自動帶上。',
      },
      {
        id: 'q6',
        prompt: '登入成功後，後端會回傳什麼給前端？',
        options: [
          { id: 'a', label: '使用者的密碼' },
          { id: 'b', label: 'JWT（像是號碼牌，證明你是誰）' },
          { id: 'c', label: '資料庫的所有資料' },
          { id: 'd', label: '伺服器的密碼' },
        ],
        correctOptionId: 'b',
        explanation: '登入成功後，後端會產生一張「號碼牌」（JWT）回傳給前端，前端存起來後，之後每次請求都帶著它來證明身份。',
      },
      {
        id: 'q7',
        prompt: 'JWT 號碼牌過期後會怎樣？',
        options: [
          { id: 'a', label: '會自動延長有效期限' },
          { id: 'b', label: '帳號會被刪除' },
          { id: 'c', label: '需要重新登入，拿一張新的號碼牌' },
          { id: 'd', label: '什麼都不會發生，永遠有效' },
        ],
        correctOptionId: 'c',
        explanation: 'JWT 有設定過期時間（例如 30 天），過期後後端會說「你的號碼牌過期了」，使用者需要重新登入取得新的 JWT。',
      },
      {
        id: 'q8',
        prompt: '在 Chrome 開發者工具中，要去哪裡看 LocalStorage 的內容？',
        options: [
          { id: 'a', label: 'Network 面板' },
          { id: 'b', label: 'Console 面板' },
          { id: 'c', label: 'Application 面板' },
          { id: 'd', label: 'Elements 面板' },
        ],
        correctOptionId: 'c',
        explanation: '打開 Chrome 開發者工具（F12），點選 Application 面板，就可以在左側看到 LocalStorage、Cookie 等儲存資料。',
      },
      {
        id: 'q9',
        prompt: '如果手動刪除瀏覽器裡存的 JWT（號碼牌），會發生什麼事？',
        options: [
          { id: 'a', label: '什麼都不會發生' },
          { id: 'b', label: '伺服器會說「你是誰？」，需要重新登入' },
          { id: 'c', label: '帳號會被停權' },
          { id: 'd', label: '網站會當機' },
        ],
        correctOptionId: 'b',
        explanation: '如果刪除瀏覽器裡存的 JWT，瀏覽器就沒有「號碼牌」了，伺服器不知道你是誰，會要求你重新登入。',
      },
      {
        id: 'q10',
        prompt: '為什麼離開電腦前要記得鎖定螢幕？',
        options: [
          { id: 'a', label: '怕螢幕燒壞' },
          { id: 'b', label: '別人可能打開 DevTools 偷走你的 JWT，冒充你登入' },
          { id: 'c', label: '電腦會自動關機' },
          { id: 'd', label: '沒有什麼特別原因，只是習慣' },
        ],
        correctOptionId: 'b',
        explanation: '如果電腦沒鎖定，別人可以打開 DevTools 看到你的 JWT，複製到自己電腦就能冒充你登入！所以離開電腦前要記得鎖定螢幕。',
      },
    ],
  },

  // ===== 測驗後對話 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(看著成績) 你完成測驗了！成績我記下來囉。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '今天學了很多重要的概念！JWT 讓我們可以在不查詢資料庫的情況下驗證使用者身份，效能很好。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '對！JWT 就像號碼牌，登入時後端給我，之後每次請求都帶著它！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(點頭) 而且要記住，Token 就像鑰匙，被偷走別人就能冒充你。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '所以要注意：JWT_SECRET 放在 .env、設定合理的過期時間、使用 HTTPS 傳輸！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '了解！還有離開電腦要記得鎖定螢幕，保護我的 JWT！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(欣慰) 很好！這些都是工作上很重要的習慣。好，今天就到這裡！',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '謝謝海克絲！今天學到很多！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(揮揮手) 回去試試用 DevTools 看看 LocalStorage 吧！明天見！',
    scene: 'normal',
    coachExpression: 'praise',
  },

  // ===== 慶祝完成 =====
  {
    type: 'celebration',
    chapterTitle: '第八天：JWT 與身份驗證',
    scene: 'normal',
    coachExpression: 'praise',
  },
]

export const chapter8: ChapterConfig = {
  id: 8,
  title: '第八天：JWT 與身份驗證',
  nodes,
}
