import type { ChapterConfig, ChapterNode } from './types'

const nodes: ChapterNode[] = [
  // ===== 開場對話：海克絲發現 Logo 忘了改 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '糟糕！我跟合夥人昨天看網站的時候發現，Logo 忘了改掉！',
    scene: 'meeting',
    coachExpression: 'shocked',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '今日任務文件：https://hackmd.io/YAjRRYJhSMqm_eRp0gnHJQ?view',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '忘了改？怎麼說？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '你看，現在網站上的 Logo 是「LiveFit+」，但我們目前應該要用「LiveFit」才對。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '「+」有什麼差別嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那個「+」是要留給之後用的。我們才剛起步，現在應該先叫 LiveFit 就好。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '等之後平台做起來了、會員變多了、功能更完整了，再升級成 LiveFit+。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那個「+」代表的是進化版，就像 iPhone 變成 iPhone Plus 一樣。現在就用掉，以後要升級就沒梗了。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '原來如此！所以要把「+」先拿掉，等 2.0 再加回來？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '沒錯！設計師已經做好正確的 Logo 了，檔名是 logo-text-v2.png，你幫我換上去。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(指著螢幕上的 Logo) 話說，如果我現在要你改這個 Logo，你知道要去哪裡找檔案嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '呃⋯⋯這個專案資料夾這麼多層，Logo 到底放在哪？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(微微一笑) 別急，改東西之前，要先搞懂專案的資料夾結構。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: 'Logo 這種圖片屬於「靜態資源」，不會隨著使用者操作而變動的東西，通常會放在 public/ 資料夾裡。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '等等，什麼是「靜態資源」？那有「動態」的嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(露出欣慰的微笑) 問得好！這個觀念很重要，搞懂之後你才知道要去哪裡改東西。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '來，我先說一個災難故事給你聽⋯⋯',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 災難故事：教練資料寫死的問題 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '你知道前任後端工程師是怎麼處理教練列表的嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '不知道⋯⋯怎麼做的？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '他把所有教練的資料都「寫死」在前端程式碼裡。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '什麼王小明、李小華、50 個教練的名字、照片、專長⋯⋯全部直接寫在 HTML 裡面。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '這樣有什麼問題嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '問題可大了！有一天我打電話給他說：「王小明教練離職了，幫我從網站上移除。」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '他說好，然後打開程式碼，找到那段 HTML，刪掉。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '我又說：「對了，李小華要改名叫李大華，順便更新他的照片。」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '他說好⋯⋯繼續改程式碼。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '我又說：「還有，我們新簽了 10 個教練，資料 Email 給你了。」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '然後他就崩潰了。',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '(冒冷汗) 我好像知道問題在哪了⋯⋯',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '沒錯！每次教練資料變動，都要改程式碼、重新部署網站。萬一改錯，網站就爆炸了。',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 選擇題：測試理解 =====
  {
    type: 'choice',
    prompt: '你覺得教練資料應該放在哪裡比較好？',
    options: [
      {
        id: 'a',
        label: '繼續寫死在 HTML 裡',
        response: '(搖頭) 這樣每次資料變動都要改程式碼，太沒效率了，而且容易出錯。',
        responseExpression: 'sigh',
        isCorrect: false,
      },
      {
        id: 'b',
        label: '放在資料庫，透過 API 取得',
        response: '(拍手) 答對了！把資料存在資料庫，需要的時候透過 API 取得，這樣改資料就不用動到程式碼了。',
        responseExpression: 'praise',
        isCorrect: true,
      },
      {
        id: 'c',
        label: '寫在 CSS 檔案裡',
        response: '(忍不住笑) CSS 是用來設定樣式的，不是存資料的地方啦！',
        responseExpression: 'biglaugh',
        isCorrect: false,
      },
      {
        id: 'd',
        label: '放在 public/ 資料夾',
        response: 'public/ 資料夾是放「靜態資源」的，像是圖片、Logo。教練資料會經常變動，不適合放這裡。',
        responseExpression: 'normal',
        isCorrect: false,
      },
    ],
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 解釋靜態 vs 動態 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '你剛剛提到的「靜態」和「動態」，這是很重要的觀念。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '讓我用簡報解釋給你聽。',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 靜態 vs 動態 互動簡報 =====
  {
    type: 'interactiveSlide',
    slideId: 'static-dynamic',
    title: '靜態 vs 動態 互動實驗室',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 簡報後對話 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '怎麼樣？現在知道靜態和動態的差別了吧！',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '原來如此！Logo 是靜態的，去 public/ 找；教練資料是動態的，要去資料庫改。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(滿意地點頭) 完全正確！你學得很快嘛。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '等等，那像是教練自己要新增課程的話呢？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '教練登入自己帳號，就可以用介面新增課程，不用勞煩工程師改程式碼嘍？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(露出欣慰的微笑) 沒錯！這就是動態資料的好處。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '讓我透過示範給你看，教練是怎麼透過網頁新增課程的。',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 教練後台互動簡報 =====
  {
    type: 'interactiveSlide',
    slideId: 'coach-backend',
    title: '教練後台：新增課程流程',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 互動簡報後對話 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '看到了嗎？教練自己操作介面，資料就存進資料庫了。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '使用者刷新網頁，就能看到最新的課程列表。完全不需要工程師介入！',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '原來如此！這就是為什麼動態資料要存在資料庫的原因。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那我再考考你幾個問題，確認你真的懂了。',
    scene: 'meeting',
    coachExpression: 'normal',
  },

  // ===== 測驗題目 =====
  {
    type: 'quiz',
    title: '靜態資源 vs 動態資料 小考',
    scene: 'meeting',
    coachExpression: 'praise',
    questions: [
      {
        id: 'q1',
        prompt: '如果把所有教練資料「寫死」在前端程式碼裡，會發生什麼問題？',
        options: [
          { id: 'a', label: '網站跑得比較快' },
          { id: 'b', label: '每次教練資料變動都要改程式碼並重新部署' },
          { id: 'c', label: '教練可以自己修改資料' },
        ],
        correctOptionId: 'b',
        explanation: '寫死的資料每次變動都需要改程式碼並重新部署，非常沒效率，而且容易出錯。',
      },
      {
        id: 'q2',
        prompt: '為什麼教練資料不適合當作「靜態資源」？',
        options: [
          { id: 'a', label: '因為教練資料太大' },
          { id: 'b', label: '因為教練資料會經常變動（新增、修改、刪除）' },
          { id: 'c', label: '因為靜態資源比較貴' },
        ],
        correctOptionId: 'b',
        explanation: '教練會離職、新進、改名、換照片，資料經常變動，所以應該存在資料庫。',
      },
      {
        id: 'q3',
        prompt: '以下哪個屬於「靜態資源」？',
        options: [
          { id: 'a', label: '會員的個人資料' },
          { id: 'b', label: '網站的 Logo 圖片' },
          { id: 'c', label: '課程的預約紀錄' },
        ],
        correctOptionId: 'b',
        explanation: 'Logo 幾乎不會變動，屬於靜態資源。會員資料和預約紀錄會經常變動，是動態資料。',
      },
      {
        id: 'q4',
        prompt: '以下哪個屬於「動態資料」？',
        options: [
          { id: 'a', label: '網站的背景圖片' },
          { id: 'b', label: '網站的 favicon 小圖示' },
          { id: 'c', label: '教練列表' },
        ],
        correctOptionId: 'c',
        explanation: '教練列表會隨著教練新增或離職而變動，是動態資料，應該存在資料庫。',
      },
      {
        id: 'q5',
        prompt: '靜態資源通常放在專案的哪個資料夾？',
        options: [
          { id: 'a', label: 'src/pages/' },
          { id: 'b', label: 'public/ 或 src/assets/' },
          { id: 'c', label: 'node_modules/' },
        ],
        correctOptionId: 'b',
        explanation: '靜態資源通常放在 public/（不會被編譯）或 src/assets/（會被編譯處理）。',
      },
      {
        id: 'q6',
        prompt: '在 LiveFit 專案中，Logo 圖片放在哪裡？',
        options: [
          { id: 'a', label: 'frontend/src/components/' },
          { id: 'b', label: 'frontend/public/' },
          { id: 'c', label: 'backend/images/' },
        ],
        correctOptionId: 'b',
        explanation: 'Logo 是靜態資源，放在 frontend/public/ 資料夾。',
      },
      {
        id: 'q7',
        prompt: '如果要修改網站使用的 Logo，除了換圖片檔案，還需要改什麼？',
        options: [
          { id: 'a', label: '只要換圖片就好，不用改其他東西' },
          { id: 'b', label: '找到引用這張圖片的程式碼，改成新的檔名' },
          { id: 'c', label: '重新安裝整個專案' },
        ],
        correctOptionId: 'b',
        explanation: '換圖片後，要開啟 LayoutHeader.vue 檔案，找到引用圖片的程式碼，把圖片檔名換成新的。',
      },
      {
        id: 'q8',
        prompt: '用 LiveFit 來比喻，「Logo」和「教練列表」分別對應什麼？',
        options: [
          { id: 'a', label: 'Logo = 動態資料，教練列表 = 靜態資源' },
          { id: 'b', label: 'Logo = 靜態資源，教練列表 = 動態資料' },
          { id: 'c', label: '兩個都是靜態資源' },
        ],
        correctOptionId: 'b',
        explanation: 'Logo 很少換（靜態資源），教練列表隨時可能變動（動態資料）。',
      },
      {
        id: 'q9',
        prompt: '動態資料的正確處理方式是？',
        options: [
          { id: 'a', label: '直接寫死在 HTML 裡面' },
          { id: 'b', label: '存在資料庫，前端透過 API 取得' },
          { id: 'c', label: '放在 public/ 資料夾' },
        ],
        correctOptionId: 'b',
        explanation: '動態資料應該存在資料庫，前端透過 API 請求後端，後端從資料庫取得資料再回傳。',
      },
    ],
  },

  // ===== 測驗完成後的對話 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(滿意地點頭) 很好！你已經掌握靜態和動態的觀念了。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那現在你應該知道怎麼換 Logo 了吧？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '知道了！去 frontend/public/ 找到圖片，然後去 LayoutHeader.vue 把檔名改成新的。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '(拍手) 完全正確！',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '對了，設計師做好的新 Logo 在這裡，你先下載下來。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '這是新版 Logo（logo-text-v2.png），請在圖片上按右鍵 → 另存圖片',
    scene: 'meeting',
    coachExpression: 'normal',
    image: '/images/logo-text-v2.png',
    showSaveHint: true,
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '下載好之後，把這張圖片放到 frontend/public/ 資料夾裡面。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '然後打開 LayoutHeader.vue，把 Logo 的檔名從 logo-text.png 改成 logo-text-v2.png。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '了解！我這就去換 Logo。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '記得換完之後重新整理網頁，確認 Logo 有更新。如果沒變，可能是瀏覽器快取，按 Ctrl+F5 強制重新整理試試（Mac 是按 Cmd+R）。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '對了，以後遇到要改東西，先問自己：這個東西會經常變動嗎？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '會經常變動的，去資料庫改；不會變動的，去檔案改。搞清楚這點，找東西就快多了。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '那接下來就拜託你嘍！加油！',
    scene: 'meeting',
    coachExpression: 'praise',
  },

  // ===== 業界彩蛋 =====
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '對了，考你一個業界小知識。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '假設你是新人工程師，到職第一天主管跟你說：「幫我改個 Logo，應該很快吧？」',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '在大型公司的複雜專案中，你覺得實際上可能要多久？',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'choice',
    prompt: '改個 Logo 實際上要多久？',
    scene: 'meeting',
    coachExpression: 'normal',
    options: [
      {
        id: 'a',
        label: '5 分鐘，不就換張圖嗎',
        response: '(搖頭) 那是主管心裡想的時間啦！實際上新人要面對的可多了⋯⋯',
        responseExpression: 'normal',
        isCorrect: false,
      },
      {
        id: 'b',
        label: '1～2 小時，找一下檔案而已',
        response: '(搖頭) 太樂觀了！那是在小專案或你已經很熟的情況。大型專案可沒這麼簡單⋯⋯',
        responseExpression: 'normal',
        isCorrect: false,
      },
      {
        id: 'c',
        label: '3～5 天，甚至更久',
        response: '(點頭) 沒錯！你很有業界 sense。主管心裡想「不就換張圖？」但新人實際上要面對的可多了⋯⋯',
        responseExpression: 'praise',
        isCorrect: true,
      },
    ],
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '搞懂專案架構 1～2 小時\n等權限開通 1 天\n問同事圖片放哪結果他在開會等半天\n本地環境跑不起來找 DevOps 等半天\n發 PR 等 Code Review 數小時到隔天\nCI/CD 跑失敗查原因 1～2 小時\n部署測試環境 PM 要驗收等半天\n上 Production 發現 CDN 快取是舊的再等 1 小時\n⋯⋯加一加，就是 3～5 天了！',
    scene: 'meeting',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '所以先搞懂專案結構真的很重要，懂了之後才能越來越快。',
    scene: 'meeting',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '我知道了！那我現在就去把 Logo 換掉。',
    scene: 'meeting',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '好，交給你嘍！加油！',
    scene: 'meeting',
    coachExpression: 'praise',
  },

  // ===== 慶祝完成 =====
  {
    type: 'celebration',
    chapterTitle: '第四天：改一個 Logo 而已',
    scene: 'meeting',
    coachExpression: 'praise',
  },
]

export const chapter4: ChapterConfig = {
  id: 4,
  title: '第四天：改一個 Logo 而已',
  nodes,
}
