import type { ChapterConfig, ChapterNode } from './types'
import { endings } from '../config/endings'

// 壞結局 - 過勞
const nodes: ChapterNode[] = [
  // === 上線當晚 ===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '專案勉強上線了，但到處都是 Bug。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你看著滿屏的錯誤回報，開始瘋狂地修復。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：完蛋了... 海姐一定會發現我根本不適任...）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：我不能讓她失望。她錄取我... 搞不好本來就是個錯誤。）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '凌晨一點...兩點...三點...',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你灌下今晚第四杯濃縮咖啡。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '再一下... 再修一個就好...',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '螢幕上的字開始變得模糊。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：這些 Bug... 海姐之前好像有提過類似的問題...）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：早知道她在教的時候，我就認真聽了...）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：她說過的那些東西，我當時怎麼都沒放在心上...）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你想起今天下午海克絲交代的話。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（回憶）「{name}，上線後不管發生什麼事，今晚十點前一定要離開公司。」',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：這... 這是一種考驗吧？她是在測試我夠不夠拼...）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你用力揉了揉眼睛，繼續敲著鍵盤。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '肩膀傳來劇烈的痠痛，但你選擇忽略。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：海姐之前也說過要注意肩膀... 我怎麼什麼都沒聽進去...）',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '突然，視線開始發黑。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '不、不行... 還有三個 Bug...',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '手機響了。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '來電顯示：海姐',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '喂？{name}？你還在公司嗎？',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你想說話，但聲音卡在喉嚨。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '{name}？你還好嗎？',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '回答我！{name}！',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '手機從手中滑落。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你聽見海克絲在電話那頭大喊著什麼。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '但那聲音越來越遠...',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '像是隔著一層厚厚的水。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '畫面逐漸變黑。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  // === 黑幕中 ===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '黑暗中，隱約傳來一個熟悉的聲音。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（遠遠的）{name}... 你聽得到嗎...？',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（遠遠的）拜託... 回答我...！',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '那聲音越來越模糊...',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（幾乎聽不見）如果... 我能早點發現就好了...',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '遠方，隱約傳來救護車的聲音。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '嗚——嗚——',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '海克絲和救護人員的身影，從遠方緩緩走來。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '但你已經看不清楚了。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '一切，歸於寂靜。',
    scene: 'dark',
    coachExpression: 'normal',
  },
  // === 結局完成 ===
  {
    type: 'endingComplete',
    endingType: 'bad',
    title: endings.bad.title,
    icon: endings.bad.icon,
    color: endings.bad.color,
    scene: 'dark',
    coachExpression: 'normal',
  },
]

export const endingBad: ChapterConfig = {
  id: endings.bad.chapterId,
  title: `結局：${endings.bad.title}`,
  nodes,
}
