import type { ChapterConfig, ChapterNode } from './types'
import { endings } from '../config/endings'

// 普通結局 - 封印
const nodes: ChapterNode[] = [
  // === 清晨六點（在家，海姐不出現）===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '清晨六點，你被手機震動吵醒。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '不是鬧鐘，是系統通知。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '📱 系統：「LiveFit 已成功部署上線。」',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（揉揉眼睛）「上線了...？」',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你下意識地打開後台。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '三個 Bug 回報。都是小問題，但確實存在。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（盯著螢幕）「...果然。」',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：我就知道。還是有漏掉的地方。）',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你嘆了口氣，開始逐一檢視錯誤訊息。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '手機又震動了一下。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你期待看到海克絲的訊息。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '但只是系統推播：「您有 3 則未讀通知。」',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：...她沒傳訊息。）',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：是不是因為這幾個 Bug，她很失望？）',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你放下手機，盯著天花板。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '專案上線了。這是事實。',
    scene: 'home',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '但心裡總覺得...好像少了什麼。',
    scene: 'home',
    coachExpression: 'normal',
  },

  // === 公司，早上九點 ===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '【公司，早上九點】',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你比平常早到公司，海克絲已經在了。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '她正看著電腦，手邊放著一杯還在冒煙的咖啡。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（抬頭）「早。坐下吧。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（站得筆直）「海姐，關於那三個 Bug，我已經看過了，我現在馬上——」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（打斷）「{name}。」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「坐下。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你乖乖坐下，背挺得像根竹竿。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（轉過螢幕讓你看）「你看這個。」',
    scene: 'normal',
    coachExpression: 'proud',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '螢幕上是 LiveFit 的後台數據。',
    scene: 'normal',
    coachExpression: 'proud',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「上線十二小時，87 個人註冊，0 個系統崩潰。」',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「你知道這代表什麼嗎？」',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（低頭）「...但是有 3 個 Bug...」',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（嘆氣）「我問你，健身的時候，有人第一天就能硬舉 100 公斤嗎？」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（愣住）「...沒有。」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「那有人第一次寫的系統，完全沒有 Bug 嗎？」',
    scene: 'normal',
    coachExpression: 'confused',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '「...」',
    scene: 'normal',
    coachExpression: 'confused',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（語氣放緩）「{name}，你做到了。專案上線了，系統穩定運作。」',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「那三個 Bug，我們今天一起修就好。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你聽著她的話，但心裡那個聲音還是很大聲。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：可是...如果我再仔細一點，就不會有這些問題了...）',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（看著你的表情，沉默了一下）',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「你是不是覺得，99 分跟 0 分一樣？」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（抬頭）「...蛤？」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（站起來，走到窗邊）「我以前也這樣。」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「覺得只要不是 100 分，就是失敗。只要有一個漏洞，之前的努力就全部白費。」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（轉頭看你）「但這種想法，會把你封印住的。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '「封印...？」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「你會困在『不夠好』的牢籠裡，永遠走不出來。」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「明明已經做到 99 分了，卻只盯著那 1 分看。」',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你低下頭，不知道該說什麼。',
    scene: 'normal',
    coachExpression: 'sigh',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（走回座位，語氣變得溫和）',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「{name}，我不是要你放棄追求完美。」',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「我是希望你在追求的路上，也能看見自己已經走了多遠。」',
    scene: 'normal',
    coachExpression: 'proud',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你抬起頭，看著海克絲。',
    scene: 'normal',
    coachExpression: 'proud',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '她的表情沒有失望，只有一種...你看不太懂的東西。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「今天的任務：修完那三個 Bug，然後六點準時下班。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「這是老闆的命令。」',
    scene: 'normal',
    coachExpression: 'proud',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（點頭）「...好。」',
    scene: 'normal',
    coachExpression: 'proud',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '（微微一笑）「走吧，先去吃早餐。修 Bug 之前，先把自己餵飽。」',
    scene: 'normal',
    coachExpression: 'biglaugh',
  },

  // === 傍晚，離開公司 ===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '【傍晚，離開公司】',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '六點整，你關上電腦。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: 'Bug 修完了。系統運作正常。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '但心裡那個聲音，還是隱隱作響。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：下次...我要做得更好。）',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（內心：不能再讓海姐幫我收尾了。）',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你走出公司，天色還亮著。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '這是你入職以來，第一次在天黑之前離開。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '風吹過來，有點涼。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '（看著天空）',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '「...也許，我還需要再努力一點吧。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你背起背包，往車站走去。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '腳步不快，但很穩。',
    scene: 'normal',
    coachExpression: 'normal',
  },

  // === 結局完成 ===
  {
    type: 'endingComplete',
    endingType: 'normal',
    title: endings.normal.title,
    icon: endings.normal.icon,
    color: endings.normal.color,
    scene: 'normal',
    coachExpression: 'normal',
  },
]

export const endingNormal: ChapterConfig = {
  id: endings.normal.chapterId,
  title: `結局：${endings.normal.title}`,
  nodes,
}
