import type { ChapterConfig, ChapterNode } from './types'
import { endings } from '../config/endings'

// 完美結局 - 覺醒（含彩蛋結局 - 傳承）
const nodes: ChapterNode[] = [
  // === 完美結局部分 ===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '陽光照進房間，你被手機訊息吵醒。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '早安，正式的後端工程師。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: 'LiveFit 第一天就有 500 人註冊，後端穩穩的，沒有任何 Bug。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你看著訊息，嘴角不自覺地上揚。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '還記得第一天你連環境都架不起來嗎？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '現在的你，已經能獨立扛起整個後端了。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '這是你應得的。記住這種感覺——穩健帶來的踏實。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '後端的路還很長，但我相信你已經準備好了。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '加油，{name}。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  // 完美結局完成節點
  {
    type: 'endingComplete',
    endingType: 'true',
    title: endings.true.title,
    icon: endings.true.icon,
    color: endings.true.color,
    canTriggerHidden: true,
    scene: 'normal',
    coachExpression: 'praise',
  },
  // === 彩蛋結局部分 ===
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你正準備關掉手機，突然收到一封新信件。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '寄件者：海克絲\n主旨：給你的一封信',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你點開信件。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '{name}，\n\n恭喜你正式成為正職員工！你好棒！\n\n附件裡有一個壓縮檔，是我想送給你的禮物。\n\n密碼的話...你應該知道的 😉\n\n—— 海姐',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你看著附件，想起了第七天在資料庫裡看到的那串亂碼。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'passwordInput',
    prompt: '請輸入解壓縮密碼...',
    hint: '提示：還記得第七天拿到的那串亂碼嗎？',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '解壓縮成功！',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '裡面是一個影片檔：「給未來的你.mp4」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你點開播放。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '海克絲出現在畫面中，背景是健身房的辦公室。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '嗨，{name}。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '如果你看到這個影片，代表你真的做到了。全部的測驗都答對，還找到了那串亂碼。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '我想跟你分享一些事情。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '她停頓了一下，眼神變得柔和。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '看到你，就像是看到以前的我一樣。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '以前的我剛進入接案公司，雖然每天都忙到三更半夜，但至少團隊成員感情都很不錯。再加上後端工程師可以整合很多系統，會感到很有成就感。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '但後來...換了新主管，接了很多不良客戶。加班到凌晨變成家常便飯。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '更重要的是，我很內耗。不懂得拒絕，不懂得要好好照顧自己。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '她苦笑了一下。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '甚至還暈倒，搭上救護車呢。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '是後來遇到瑜伽跟健身，才慢慢平緩下來。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '所以我希望你，一定要以自己為優先。好好照顧好自己，才有多餘的能力照顧他人。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '她的表情變得認真。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '再次恭喜你成為正職。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '其實當我第七天看到你認真攻略資料庫的時候，我就認定你一定可以突破這次上線的挑戰。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '這樣的決心和耐力，表示你真的很有潛能成為軟體工程師。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '很多人都會認為工程師需要天賦才可以。但其實以前的我，也是天天被前輩念到長大。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '前輩跟我說過一句話——',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '「人的一生就像是馬拉松。我們很常高估自己一年可以做的事，卻低估自己二三十年後的成長。」',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '慢慢成長，才是比較快的。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '影片畫面開始慢慢變暗。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '看到這裡，影片也即將到尾聲了。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '最後想和你說三件事。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '第一，你真的很棒。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '第二，你不用一開始就很厲害，但要開始才會很厲害。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '第三...',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '她露出溫暖的笑容。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '只要你不放棄自己，海姐也不會放棄你。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '海克絲',
    text: '加油，{name}。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '影片結束。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '旁白',
    text: '你關掉影片，看著窗外的陽光。',
    scene: 'normal',
    coachExpression: 'normal',
  },
  {
    type: 'dialogue',
    speaker: '你',
    text: '謝謝你，海姐。',
    scene: 'normal',
    coachExpression: 'praise',
  },
  {
    type: 'endingComplete',
    endingType: 'hidden',
    title: endings.hidden.title,
    icon: endings.hidden.icon,
    color: endings.hidden.color,
    scene: 'normal',
    coachExpression: 'praise',
  },
]

export const endingTrue: ChapterConfig = {
  id: endings.true.chapterId,
  title: `結局：${endings.true.title} / ${endings.hidden.title}`,
  nodes,
}
